name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    # strategy:
    #   matrix:
    #    dotnet-version: [ '8.0.x', '6.0.x' ]
    # env:
    #  DOTNET_INSTALL_DIR: "${{ github.workspace }}/NUnitTestProject"

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Display structure of working directory
        run: ls -R
        working-directory: ${{ github.workspace }}
        
      - name: restore/build/test
        shell: pwsh
        run: |
          dotnet restore
          dotnet build
          dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"  || true
        working-directory: "${{ github.workspace }}/NUnitTestProject"

      - name: Display structure of working directory
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: '**/test-results.trx'                            
          reporter: dotnet-trx
          fail-on-error: true
        
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: "**/${{ github.workspace }}/NUnitTestProject/TestResults/test-results.trx"
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
