name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     dotnet-version: [ '8.0.x', '6.0.x' ]
    env:
     DOTNET_INSTALL_DIR: "${{ github.workspace }}/NUnitTestProject"

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Display structure of working directory
        run: ls -R
        working-directory: ${{ github.workspace }}
      - name: restore/build/test
        run: |
          dotnet restore ./NUnitTestProject/NUnitTestProject.csproj
          dotnet build
          dotnet test
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
          # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
